DATASET = "/Users/haritha/Downloads/uni/"
WORKING_DATASET = "data/uni/"

DATA_PATH = f"{DATASET}data_seg"
ORIG_DATA_PATH = f"{DATASET}data"

MODEL_FOLDER = f"{WORKING_DATASET}models"
FEATURES = f"{WORKING_DATASET}features_prep_mean_int_area_v2"
RAW_FEATURES = f"{WORKING_DATASET}features"
RESULTS = f"{WORKING_DATASET}results"

GLOBAL = "global"
TRAIN = "train"
PRETRAINED = "pretrained"
AUTOENCODERS = "autoencoders"
WORD_AUTOENCODER = "word"
CONV_AUTOENCODERS = "conv_autoencoders"
V_AUTOENCODERS = "v_autoencoders"
VAL_OWN = "val_own"
VAL = "val"
TEST = "test"
AND = "and"
THE = "the"
SAMPLE = "sample"
CHARS = "chars"
LOCAL_TRAIN = "local_train"
LOCAL_PRED = "local_pred"
HIST = "hist"
PCA = "pca"
